# choosing files to be annotated

perhaps make a datasheet, all of the 5s clips, file paths, species detected (filtered), date, site, session (dawn/dusk), embedding parquet_path. in one .csv would be helpful i think.

Need to understand how the parquet embeddings work properly!

In [121]:
import pandas as pd
import polars as pl

# make panda display width 150 and max columns 20
pd.set_option('display.max_columns', 15)
pd.set_option('display.width', 300)
pl.Config.set_tbl_cols(15)
pl.Config.set_tbl_width_chars(300)

polars.config.Config

In [122]:
PT_ROOT = '/Users/ash/phd/wytham_pam_data/embeddings/2025'
PT_CHECKPOINT = f'{PT_ROOT}/checkpoint-10000'

In [123]:
emb = pd.read_parquet(PT_ROOT+'/G2-2/embeddings_partitioned/0/part-0.parquet', engine="pyarrow")
print(emb.shape)          # e.g. (14400, 1285)  — 14400 clips, 1280 emb cols + 5 metadata cols
print(emb.columns)    # file, file_path, chunk_idx, start_time, end_time, emb_0, ...

(800, 1541)
Index(['file', 'file_path', 'chunk_idx', 'start_time', 'end_time', 'emb_0', 'emb_1', 'emb_2', 'emb_3', 'emb_4',
       ...
       'emb_1526', 'emb_1527', 'emb_1528', 'emb_1529', 'emb_1530', 'emb_1531', 'emb_1532', 'emb_1533', 'emb_1534', 'emb_1535'], dtype='str', length=1541)

In [5]:
print(emb[(emb['file']=='20250714_194600_2')&(emb['chunk_idx']==2)])  # e.g. 0: 14400, 1: 14400, ... 9: 14400

                file                                          file_path  chunk_idx  start_time  end_time     emb_0     emb_1  ...  emb_1529  emb_1530  emb_1531  emb_1532  emb_1533  emb_1534  emb_1535
2  20250714_194600_2  /mnt/bio-lv-colefs01/2025-wytham-acoustics/G2-...          2        10.0      15.0 -0.044805 -0.092061  ... -0.070401 -0.114337  0.006316 -0.016656  0.045278 -0.030567 -0.128555

[1 rows x 1541 columns]

In [120]:

# Load the canonical index
index = pl.read_parquet("/Users/ash/Library/CloudStorage/OneDrive-Nexus365/PHD/Wytham_PAM/perch-cpu-inference/wytham_labels/output/canonical_clip_index.parquet")

# Query a specific clip
clip = index.filter(pl.col("clip_id") == "G2-2_20250714_194600_0")
print(clip)
# Get the embedding for this clip
emb_path = clip["embedding_path"][0]
emb_df = pl.read_parquet(emb_path)
clip_embedding = emb_df.filter(
    (pl.col("chunk_idx") == 0) & 
    (pl.col("file_path").str.contains("20250714_194600"))
)

print(clip_embedding.select(pl.col("^emb_.*$")))  # All 1280 embedding dimensions

shape: (1, 24)
┌────────────────────────┬──────┬──────────────────────────────────┬─────────────────────┬───────────┬────────────┬──────────┬──────────────┬───┬──────────────┬────────────┬──────────────────────────────────┬───────────────────────┬──────────────────────────────────┬──────────────────┬─────────────┐
│ clip_id                ┆ site ┆ audio_path                       ┆ file_name           ┆ chunk_idx ┆ start_time ┆ end_time ┆ duration_sec ┆ … ┆ top1_species ┆ top1_score ┆ top_species                      ┆ top_scores            ┆ embedding_path                   ┆ embedding_exists ┆ file_exists │
│ ---                    ┆ ---  ┆ ---                              ┆ ---                 ┆ ---       ┆ ---        ┆ ---      ┆ ---          ┆   ┆ ---          ┆ ---        ┆ ---                              ┆ ---                   ┆ ---                              ┆ ---              ┆ ---         │
│ str                    ┆ str  ┆ str                              ┆ str                 ┆ i64       ┆ f64        ┆ f64      ┆ f64          ┆   ┆ str          ┆ f64        ┆ list[str]                        ┆ list[f64]             ┆ str                              ┆ bool             ┆ bool        │
╞════════════════════════╪══════╪══════════════════════════════════╪═════════════════════╪═══════════╪════════════╪══════════╪══════════════╪═══╪══════════════╪════════════╪══════════════════════════════════╪═══════════════════════╪══════════════════════════════════╪══════════════════╪═════════════╡
│ G2-2_20250714_194600_0 ┆ G2-2 ┆ /mnt/bio-lv-colefs01/2025-wyth…  ┆ 20250714_194600.WAV ┆ 0         ┆ 0.0        ┆ 5.0      ┆ 5.0          ┆ … ┆ Corvus corax ┆ 8.05476    ┆ ["Corvus corax", "Meleagris ga…  ┆ [8.05476, 6.381258, … ┆ /Users/ash/phd/wytham_pam_data…  ┆ true             ┆ false       │
│                        ┆      ┆                                  ┆                     ┆           ┆            ┆          ┆              ┆   ┆              ┆            ┆                                  ┆ 5.576178…             ┆                                  ┆                  ┆             │
└────────────────────────┴──────┴──────────────────────────────────┴─────────────────────┴───────────┴────────────┴──────────┴──────────────┴───┴──────────────┴────────────┴──────────────────────────────────┴───────────────────────┴──────────────────────────────────┴──────────────────┴─────────────┘
shape: (1, 1_536)
┌───────────┬───────────┬───────────┬──────────┬───────────┬──────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┬──────────┬──────────┬───────────┐
│ emb_0     ┆ emb_1     ┆ emb_2     ┆ emb_3    ┆ emb_4     ┆ emb_5    ┆ emb_6     ┆ emb_7    ┆ … ┆ emb_1529  ┆ emb_1530  ┆ emb_1531  ┆ emb_1532 ┆ emb_1533 ┆ emb_1534 ┆ emb_1535  │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆ ---       ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ f32       ┆ f32       ┆ f32       ┆ f32      ┆ f32       ┆ f32      ┆ f32       ┆ f32      ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      ┆ f32      ┆ f32      ┆ f32       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══════════╪══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╪══════════╪══════════╪═══════════╡
│ -0.016416 ┆ -0.140566 ┆ -0.034019 ┆ 0.132148 ┆ -0.006312 ┆ 0.024709 ┆ -0.032118 ┆ 0.018829 ┆ … ┆ -0.074416 ┆ -0.159572 ┆ -0.054437 ┆ -0.08423 ┆ 0.114944 ┆ 0.06428  ┆ -0.110233 │
└───────────┴───────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┴──────────┴──────────┴───────────┘

In [7]:
missing_embeddings = index.filter(pl.col("embedding_exists") == False)


missing_embeddings.head()

shape: (5, 24)
┌────────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ clip_id    ┆ site ┆ audio_path ┆ file_name  ┆ … ┆ top_scores ┆ embedding ┆ embedding ┆ file_exis │
│ ---        ┆ ---  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ _path     ┆ _exists   ┆ ts        │
│ str        ┆ str  ┆ str        ┆ str        ┆   ┆ list[f64]  ┆ ---       ┆ ---       ┆ ---       │
│            ┆      ┆            ┆            ┆   ┆            ┆ str       ┆ bool      ┆ bool      │
╞════════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ H9_2025021 ┆ H9   ┆ /mnt/bio-l ┆ 20250216_0 ┆ … ┆ [7.570748, ┆ /Users/as ┆ false     ┆ false     │
│ 6_063100_7 ┆      ┆ v-colefs01 ┆ 63100.WAV  ┆   ┆ 7.329322,  ┆ h/phd/wyt ┆           ┆           │
│            ┆      ┆ /2025-wyth ┆            ┆   ┆ … 6.02954… ┆ ham_pam_d ┆           ┆           │
│            ┆      ┆ …          ┆            ┆   ┆            ┆ ata…      ┆           ┆           │
│ H9_2025021 ┆ H9   ┆ /mnt/bio-l ┆ 20250216_0 ┆ … ┆ [8.078139, ┆ /Users/as ┆ false     ┆ false     │
│ 6_063100_8 ┆      ┆ v-colefs01 ┆ 63100.WAV  ┆   ┆ 6.869777,  ┆ h/phd/wyt ┆           ┆           │
│            ┆      ┆ /2025-wyth ┆            ┆   ┆ … 6.07628… ┆ ham_pam_d ┆           ┆           │
│            ┆      ┆ …          ┆            ┆   ┆            ┆ ata…      ┆           ┆           │
│ H9_2025021 ┆ H9   ┆ /mnt/bio-l ┆ 20250216_0 ┆ … ┆ [7.76244,  ┆ /Users/as ┆ false     ┆ false     │
│ 6_063100_9 ┆      ┆ v-colefs01 ┆ 63100.WAV  ┆   ┆ 6.471144,  ┆ h/phd/wyt ┆           ┆           │
│            ┆      ┆ /2025-wyth ┆            ┆   ┆ …          ┆ ham_pam_d ┆           ┆           │
│            ┆      ┆ …          ┆            ┆   ┆ 5.946932…  ┆ ata…      ┆           ┆           │
│ H9_2025021 ┆ H9   ┆ /mnt/bio-l ┆ 20250216_0 ┆ … ┆ [8.270762, ┆ /Users/as ┆ false     ┆ false     │
│ 6_063100_1 ┆      ┆ v-colefs01 ┆ 63100.WAV  ┆   ┆ 8.065734,  ┆ h/phd/wyt ┆           ┆           │
│ 0          ┆      ┆ /2025-wyth ┆            ┆   ┆ … 5.74701… ┆ ham_pam_d ┆           ┆           │
│            ┆      ┆ …          ┆            ┆   ┆            ┆ ata…      ┆           ┆           │
│ H9_2025021 ┆ H9   ┆ /mnt/bio-l ┆ 20250216_0 ┆ … ┆ [8.153281, ┆ /Users/as ┆ false     ┆ false     │
│ 6_063100_1 ┆      ┆ v-colefs01 ┆ 63100.WAV  ┆   ┆ 7.200423,  ┆ h/phd/wyt ┆           ┆           │
│ 1          ┆      ┆ /2025-wyth ┆            ┆   ┆ … 5.99047… ┆ ham_pam_d ┆           ┆           │
│            ┆      ┆ …          ┆            ┆   ┆            ┆ ata…      ┆           ┆           │
└────────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [104]:
# list of 5 missing embeddings paths
missing_embeddings_paths = missing_embeddings[["embedding_path",'checkpoint_id']].unique().head(20)
missing_embeddings[["embedding_path",'checkpoint_id']].unique().head(20)

shape: (20, 2)
┌─────────────────────────────────┬───────────────┐
│ embedding_path                  ┆ checkpoint_id │
│ ---                             ┆ ---           │
│ str                             ┆ i64           │
╞═════════════════════════════════╪═══════════════╡
│ /Users/ash/phd/wytham_pam_data… ┆ 71            │
│ /Users/ash/phd/wytham_pam_data… ┆ 95            │
│ /Users/ash/phd/wytham_pam_data… ┆ 48            │
│ /Users/ash/phd/wytham_pam_data… ┆ 120           │
│ /Users/ash/phd/wytham_pam_data… ┆ 112           │
│ …                               ┆ …             │
│ /Users/ash/phd/wytham_pam_data… ┆ 49            │
│ /Users/ash/phd/wytham_pam_data… ┆ 98            │
│ /Users/ash/phd/wytham_pam_data… ┆ 136           │
│ /Users/ash/phd/wytham_pam_data… ┆ 3             │
│ /Users/ash/phd/wytham_pam_data… ┆ 72            │
└─────────────────────────────────┴───────────────┘

In [116]:
# get embedding for a given record
clip_id = "G2-2_20250714_194600_1"
clip = index.filter(pl.col("clip_id") == clip_id)
print(clip)
emb_path = clip["embedding_path"][0]
emb_df = pl.read_parquet(emb_path)
clip_embedding = emb_df.filter(
    (pl.col("chunk_idx") == clip['chunk_idx'][0]) & 
    (pl.col("file_path").str.contains(clip_id.split('_')[1] + '_' + clip_id.split('_')[2]))  # match date and time, turns G2-2_20250714_194600_0 into 20250714_194600. (splits on _ and picks out the date and time parts)
)
print(clip_embedding)

shape: (1, 24)
┌────────────────────────┬──────┬──────────────────────────────────┬─────────────────────┬───────────┬────────────┬──────────┬──────────────┬───┬──────────────────────┬────────────┬──────────────────────────┬───────────────────────┬──────────────────────────────────┬──────────────────┬─────────────┐
│ clip_id                ┆ site ┆ audio_path                       ┆ file_name           ┆ chunk_idx ┆ start_time ┆ end_time ┆ duration_sec ┆ … ┆ top1_species         ┆ top1_score ┆ top_species              ┆ top_scores            ┆ embedding_path                   ┆ embedding_exists ┆ file_exists │
│ ---                    ┆ ---  ┆ ---                              ┆ ---                 ┆ ---       ┆ ---        ┆ ---      ┆ ---          ┆   ┆ ---                  ┆ ---        ┆ ---                      ┆ ---                   ┆ ---                              ┆ ---              ┆ ---         │
│ str                    ┆ str  ┆ str                              ┆ str                 ┆ i64       ┆ f64        ┆ f64      ┆ f64          ┆   ┆ str                  ┆ f64        ┆ list[str]                ┆ list[f64]             ┆ str                              ┆ bool             ┆ bool        │
╞════════════════════════╪══════╪══════════════════════════════════╪═════════════════════╪═══════════╪════════════╪══════════╪══════════════╪═══╪══════════════════════╪════════════╪══════════════════════════╪═══════════════════════╪══════════════════════════════════╪══════════════════╪═════════════╡
│ G2-2_20250714_194600_1 ┆ G2-2 ┆ /mnt/bio-lv-colefs01/2025-wyth…  ┆ 20250714_194600.WAV ┆ 1         ┆ 5.0        ┆ 10.0     ┆ 5.0          ┆ … ┆ Haemorhous purpureus ┆ 5.93782    ┆ ["Haemorhous purpureus", ┆ [5.93782, 5.828134, … ┆ /Users/ash/phd/wytham_pam_data…  ┆ true             ┆ false       │
│                        ┆      ┆                                  ┆                     ┆           ┆            ┆          ┆              ┆   ┆                      ┆            ┆ "Stri…                   ┆ 4.972249…             ┆                                  ┆                  ┆             │
└────────────────────────┴──────┴──────────────────────────────────┴─────────────────────┴───────────┴────────────┴──────────┴──────────────┴───┴──────────────────────┴────────────┴──────────────────────────┴───────────────────────┴──────────────────────────────────┴──────────────────┴─────────────┘
shape: (1, 1_541)
┌───────────────────┬─────────────────────────────────┬───────────┬────────────┬──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┬──────────┬──────────┬───────────┐
│ file              ┆ file_path                       ┆ chunk_idx ┆ start_time ┆ end_time ┆ emb_0     ┆ emb_1     ┆ emb_2     ┆ … ┆ emb_1529  ┆ emb_1530  ┆ emb_1531 ┆ emb_1532  ┆ emb_1533 ┆ emb_1534 ┆ emb_1535  │
│ ---               ┆ ---                             ┆ ---       ┆ ---        ┆ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---       │
│ str               ┆ str                             ┆ i64       ┆ f64        ┆ f64      ┆ f32       ┆ f32       ┆ f32       ┆   ┆ f32       ┆ f32       ┆ f32      ┆ f32       ┆ f32      ┆ f32      ┆ f32       │
╞═══════════════════╪═════════════════════════════════╪═══════════╪════════════╪══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╪══════════╪══════════╪═══════════╡
│ 20250714_194600_1 ┆ /mnt/bio-lv-colefs01/2025-wyth… ┆ 1         ┆ 5.0        ┆ 10.0     ┆ -0.009383 ┆ -0.121973 ┆ -0.028527 ┆ … ┆ -0.086469 ┆ -0.134611 ┆ 0.001673 ┆ -0.027713 ┆ 0.048809 ┆ -0.02278 ┆ -0.143627 │
└───────────────────┴─────────────────────────────────┴───────────┴────────────┴──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┴──────────┴──────────┴───────────┘